#! /usr/bin/env Rscript
## This runs testme test script inst/testme/test-progressify-foreach.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
progressify:::testme("progressify-foreach")
