#! /usr/bin/env Rscript
## This runs testme test script inst/testme/test-progressify-internals.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
progressify:::testme("progressify-internals")
