# Do not edit this file. It is generated from transpiler/R/utils.R
# by 'make transpiler-sync'. Edit the 'transpiler' package instead.

comma <- function(x, sep = ", ") paste(x, collapse = sep)
commaq <- function(x, sep = ", ") paste(sQuote(x), collapse = sep)
