on:
  workflow_dispatch:  # Enables manual triggering

name: deps-devel-checks

jobs:
  deps-devel-checks:
    timeout-minutes: 45

    runs-on: ubuntu-latest

    name: ${{ matrix.config.pkg }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { r: "release", pkg: "crossmap", url: "rossellhayes/crossmap" }
          - { r: "release", pkg: "doFuture", url: "futureverse/doFuture@develop" }
          - { r: "release", pkg: "foreach", url: "RevolutionAnalytics/foreach" }
          - { r: "release", pkg: "future.apply", url: "futureverse/future.apply@develop" }
          - { r: "release", pkg: "futurize", url: "futureverse/futurize@develop" }
          - { r: "release", pkg: "purrr", url: "tidyverse/purrr" }
          - { r: "release", pkg: "furrr", url: "futureverse/furrr" }
#          - { r: "release", pkg: "partykit", url: "partykit" }
          - { r: "release", pkg: "plyr", url: "hadley/plyr" }
 
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      ## Test in other locale (optional)
      ## R (>= 4.4.0) Note, no trailing underscore (sic!)
      _R_COMPARE_LANG_OBJECTS: eqonly
      ## R CMD check
      _R_CHECK_CRAN_INCOMING_: false
      _R_CHECK_MATRIX_DATA_: true
      _R_CHECK_SUGGESTS_ONLY_: false
      _R_CHECK_FORCE_SUGGESTS_: true
      _R_CHECK_THINGS_IN_TEMP_DIR_: true
      _R_CHECK_TESTS_NLINES_: 300
      _R_CHECK_TESTS_ELAPSED_THRESHOLD_: 0
      RCMDCHECK_ERROR_ON: note
      NOT_CRAN: true
      ## Specific to futures
#      R_FUTURE_CONNECTIONS_ONMISUSE: "error[details=TRUE]"
      R_FUTURE_GLOBALENV_ONMISUSE: "error"
      R_FUTURE_GLOBALS_ONREFERENCE: "warning"
      R_FUTURE_RNG_ONMISUSE: error
      R_FUTURE_FUTURE_EARLYSIGNAL: defunct
      R_FUTURE_FUTURE_LOCAL: defunct
      R_FUTURE_FUTURE_GC: defunct
      R_FUTURE_PLAN_EARLYSIGNAL: defunct
      R_FUTURE_RESOLVED_RUN: defunct
      ## Specific to testme
      R_TESTME_FILTER_TAGS: '"pkg-${{ matrix.config.pkg }}" %in% tags'

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::remotes
          needs: check

      - name: Install package itself (special case)
        run: |
          install.packages(".", repos = NULL, type = "source")
        shell: Rscript {0}

      - name: Install development versions of dependencies
        run: |
          pak::pak("${{ matrix.config.url }}")
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          parallelly::availableCores(which = "all")
          sapply(c(physical_cores = FALSE, logical_cores = TRUE), parallel::detectCores)
          if (require(RhpcBLASctl, quietly=TRUE)) c(get_num_procs = get_num_procs(), get_num_cores = get_num_cores(), blas_get_num_procs = blas_get_num_procs(), omp_get_num_procs = omp_get_num_procs(), omp_get_max_threads = omp_get_max_threads())
          capabilities()
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
          ## Verify LANGUAGE settings by generating a translatable error
          cat(sprintf("LANGUAGE=%s\n", sQuote(Sys.getenv("LANGUAGE"))))
          cat(sprintf("locales: %s\n", sQuote(Sys.getlocale())))
          tryCatch(log("a"), error = conditionMessage)
        shell: Rscript {0}

      - name: Check
        run: |
          rcmdcheck::rcmdcheck(
            args = c("--no-manual", "--as-cran"),
            check_dir = "check"
          )
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
